### ISSUE TITLE
Default dashboard and Saml login 

### ISSUE THREAD

**Issue by SETU-WEB** [verbb/default-dashboard#11]
### Question

Hi 
I use the Saml singe sign on plugin to allow my users to login and the default dashboard works fine with existing users but when a new user logs in a new account is automatically created for them in the members group and the dashboard doesn't show. The dashboard I setup has a lot of instructions on what to do next, so this is a bit of an issue for me. From what I can see on how the dashboard is called I can see why it doesn't work but I thought I would ask the question anyway 
Thanks for your help

**Comment by engram-design** [comment]
I can't comment on what the [SAML SSO Service Provider](https://plugins.craftcms.com/saml-sp?craft4) plugin does, we listen to the [login](https://github.com/verbb/default-dashboard/blob/0977dfe14bbce0d1aa9ef0e51d60c1b4e78f9522/src/DefaultDashboard.php#L79) event for a user, so it might be possible that the way their plugin works, this event doesn't get triggered.

From what I can tell, they [login](https://github.com/flipboxfactory/saml-sp/blob/c1991f64aa77815f3671fd4435fca3d2d884ce93/src/services/login/User.php#L101) the normal way, it may be the fact that we check if the request is a [CP](https://github.com/verbb/default-dashboard/blob/0977dfe14bbce0d1aa9ef0e51d60c1b4e78f9522/src/services/Service.php#L27) one.

Can you check your logs at `/storage/logs/default-dashboard-*.log`?

**Comment by SETU-WEB** [comment]
Yes looking at the logs ,the saml login isn't recognised in the same way as a normal login . I just found a Modify the Redirect After Successful Login option in the saml events that does the same job for me so I am going to close this one 
Thanks
