### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/default-dashboard#3]
### Description
I've configured the plugin so my default dashboard should be mirrored to others, but it doesn't seem to be happening.

### Steps to reproduce

1. Choose my own dashboard (admin) as "Default User Dashboard"
2. Toggle "Override User Dashboard" to On
3. Visit another user's dashboard
4. Their widgets seem to be completely independent of mine

### Additional info

- Plugin version: 1.0.1
- Craft version: Pro 3.0.11

**Comment by engram-design** [comment]
Out of interest, are you logging in and out to check the other users' dashboard? Other users' widgets are only refreshed on the login event. I have tested it on my end, even when switching from one account to another, and it does seem to be working...

**Comment by KatieMFritz** [comment]
I watched as other users logged in on their machines

**Comment by engram-design** [comment]
Hmmm, I'll keep investigating, but its certainly working on my end which is a pain to debug...

**Comment by KatieMFritz** [comment]
I'll try recreating again later. Don't worry about it for now. 😄

**Comment by jalendport** [comment]
Not working for me either 🤔 I'm logging into other user's account via the dropdown on the individual users and it's showing me default widgets instead of the ones I have set on my account.

**Comment by engram-design** [comment]
Hmm, still struggling to reproduce this after quite some testing. Don't suppose this is available on a staging server or something to test out your setup? Happy to get in touch via Slack (@crawf).

**Comment by outline4** [comment]
Hi, the same here.  
It shows the widgets I've added, but it also shows the default widgets.  
Craft CMS 3.0.29, Default Dashboard 1.0.2

**Comment by engram-design** [comment]
This _should_ be fixed in [1.0.3](https://github.com/verbb/default-dashboard/releases/tag/1.0.3). I believe this issue was if the user was logging in for the very first time they were getting the default widgets added alongside your nominated users' ones.

Let me know if its still an issue and will reopen.

**Comment by outline4** [comment]
The 1.0.3. release fixed the problem!  
Thanks a lot!
