### ISSUE TITLE
Default dashboard is not working anymore

### ISSUE THREAD

**Issue by romainpoirier** [verbb/default-dashboard#4]
### Description

Default dashboard is not working anymore. After log in using a fresh new account, the dashboard show the default Craft setup instead of the referenced user setup.

### Steps to reproduce

1. Add default-dashboard.php following example
2. Create a new user
3. Login using this new user account

### Additional info

- Plugin version: Craft Pro 3.1.12
- Craft version: 1.0.3

**Comment by engram-design** [comment]
Can you confirm your `userDashboard` setting correctly reflects the ID of the user you want to copy from? As in - if set to `1`, there's definitely a user set with an ID of `1`?

All seems to be working well on my system. I've tried logging in on behalf of the user, as well as logging out fully, and logging into the CP with the new user account.

**Comment by romainpoirier** [comment]
> Can you confirm your `userDashboard` setting correctly reflects the ID of the user you want to copy from? As in - if set to `1`, there's definitely a user set with an ID of `1`?

Yes.

> All seems to be working well on my system. I've tried logging in on behalf of the user, as well as logging out fully, and logging into the CP with the new user account.

Thank you for testing. So I guess this has something to do with my current plugins (or my custom module). I will try later to disable each one after the other when I get time.

- CP Field Inspect	1.0.5
- Craft Dynamic Fields	3.0.6
- Default Dashboard	1.0.3
- Do It Yourself widget	2.0.1
- Dumper	1.3.1
- Element API	2.5.4
- Imager	v2.1.4
- Mandrill	1.3.0
- Minify	1.2.9
- Redactor	2.3.1
- ServeSecret	dev-master
- Two-Factor Authentication	2.1.0-beta.2
- Typogrify	1.1.16
- Zendesk	1.0.6

**Comment by engram-design** [comment]
Its worth a shot for sure. Have continued to test a few different scenarios through the day.

Failing that, I'll add some more debugging steps to the plugin, so we can get to the bottom of it.

**Comment by engram-design** [comment]
@romainpoirier Would you be able to give the latest branch a go with logging? Run `composer require verbb/default-dashboard:dev-craft-3`, and then post your `default-dashboard.log` file?

**Comment by romainpoirier** [comment]
Thank you for investigating it. I didn't had the time to disable my module/plugins, but I have installed the `verbb/default-dashboard:dev-craft-3` version. Unfortunately, the `default-dashboard.log` file do not show up in the `storage/logs` folder, even after switching account then visiting the dashboard.

**Comment by engram-design** [comment]
Strange. Just updated with a few more bits of logging. Care to try now?

**Comment by romainpoirier** [comment]
Now the log file appeared. I've just sent it to you by email. Thank you.

**Comment by engram-design** [comment]
I believe this is because the `Two-Factor Authentication` plugin doesn't seem to be raising the Yii event `\yii\web\User::EVENT_AFTER_LOGIN`, which this plugin relies on. I might suggest that over on that plugin

**Comment by roelvanhintum** [comment]
@romainpoirier can you install the plugin with this commit number to see if this fixes it?
https://github.com/born05/craft-twofactorauthentication/commit/1cb219d58b7411d7e1fc8bbbd69c889231c98f2e

**Comment by romainpoirier** [comment]
@roelvanhintum, thanks. Perhaps a silly question, but how can I install this version using composer? This commit from the branch craft-3.1 is not yet released, I don't find how to install it.

**Comment by roelvanhintum** [comment]
@romainpoirier I had to look it up, but requiring the following should work:
```
"born05/craft-twofactorauthentication": "dev-craft-3.1#1cb219d58b7411d7e1fc8bbbd69c889231c98f2e",
```

**Comment by romainpoirier** [comment]
Thank you @roelvanhintum! @engram-design, I can confirm that it seems to fix the bug 👍.

**Comment by engram-design** [comment]
Awesome, thanks for your help @roelvanhintum!
