### ISSUE TITLE
No settings available in Backend

### ISSUE THREAD

**Issue by EternalBlack** [verbb/default-dashboard#5]
### Description

Can't seem to find the mentioned section inside the Admin CP after installation (no settings in the sidebar, nor any settings available from `/admin/settings/plugins` at the plugin itself.
Tried to use the `default-dashboard.php` file but no luck either. Doesn't seem to have any effect.

### Steps to reproduce

1. Install plugin
2. Try to access settings page

### Additional info

- Plugin version: 1.0.4
- Craft version: Craft CMS 3.1.17.1 (Pro)

**Comment by engram-design** [comment]
Should be fixed in [1.0.5](https://github.com/verbb/default-dashboard/releases/tag/1.0.5)
