### ISSUE TITLE
Useless logs in production

### ISSUE THREAD

**Issue by romainpoirier** [verbb/default-dashboard#7]
### Description

On a Craft project with a login area on front-end, default-dashboard is logging a lot of useless lines like this:

```
2019-08-26 11:22:05 [-][36297][-][info][default-dashboard] Not a CP request
2019-08-26 11:22:05 [-][36297][-][info][application] $_GET = []

$_POST = []

$_FILES = []
...
```

It would be nice:

- To disable info logs in production (only error or warning are relevant);
- And/Or disable this kind of log when a login request happens from the front-end;

### Additional info

- Plugin version: 1.0.5
- Craft version: 3.2.10

**Comment by engram-design** [comment]
Yep, had been meaning to remove these after troubleshooting some issues.

Updated in [1.0.6](https://github.com/verbb/default-dashboard/releases/tag/1.0.6)
