### ISSUE TITLE
Fatal error with Default Dashboard

### ISSUE THREAD

**Issue by ptrykulich** [verbb/default-dashboard#9]
![error default dashboard](https://user-images.githubusercontent.com/66869015/87318726-682bed00-c531-11ea-8c21-3acaccd5367b.png)
### Description

Have some problem with Default Dashboard plugin. 

### Steps to reproduce

1. Open /admin/dashboard.
2. Get fatal error.

### Additional info

-- Plugin version: 1.0.8
-- Craft version: Pro 3.4.27

**Comment by engram-design** [comment]
I don't believe this is a default dashboard issue, instead an issue with the widget `contentstats`
